### ISSUE TITLE
An idea for simplifying the logic of model building...

### ISSUE THREAD

**Issue by FHell** [PIK-ICoN/NetworkDynamics.jl#18]
Right now we have one set of variables per edge: e. Then the edge nodes have to distinguish between incoming and outgoing edges: e_s and e_d.

A cleaner way to do this would be to have one set of variables per half edge, "e_1" and "e_2" (the edge as viewed from its ends), have the edge dynamics determine these half edge variables, and then each vertex only gets the half edge variables belonging to it (the view of the incident edges from the vertex).

This is strictly _less_ general than the setup we have now, and a disadvantage is that for some systems for which the difference between the view from the ends is related by a simple sign (flow networks) we are doubling the number of edge variables.

It might be worth exploring if we can write a wrapper with this interface though.

**Comment by lindnemi** [comment]
https://github.com/FHell/NetworkDynamics.jl/commit/b6df197caf755533b4e4e6d04242aa06a72f93c2

is an attempt in this direction, taking a different approach to parts of the core loop. in combination with aggregations functions, the performance is quite good.

**Comment by lindnemi** [comment]
Default since version 0.5
