### ISSUE TITLE
Julia code on Second order Kuramoto dynamics

### ISSUE THREAD

**Issue by CRHENS** [PIK-ICoN/NetworkDynamics.jl#74]
I am reproducing a paper  (Topological Determinants of Perturbation Spreading in Networks,  Mark Timme et al, PDF is also attached ) on second-order Kuramoto dynamics where an internal perturbation (a sinusoidal force) is used in a single arbitrary node to understand the propagation of perturbation through the network. 
 Motivated by the code "kuramoto_inertial.jl" I write a small code (code is attached here, Name: ). However, I am unable to add this time-dependent perturbation in this code.
[New folder.zip](https://github.com/FHell/NetworkDynamics.jl/files/6047713/New.folder.zip)

**Comment by lindnemi** [comment]
You accidentally define a function `D(t)` that returns another function
```julia
function D(t)

 D(t)=0.1*sin(t)

end
```
It should be either `D(t) = 0.1 * sin(t)`, or
```julia
function D(t)
 return 0.1*sin(t)
end
```
Does this fix your issue?

**Comment by CRHENS** [comment]
Sorry to disturb you again.
We got another error:
"UndefVarError: odevertex not defined"
Code attached here.

**Comment by lindnemi** [comment]
Well, it says you didn't define the variable `odevertex` and indeed it is not in the script. What kind of dynamic do you want the `odevertex` to have? If you are looking for kuramoto model with inertia you can just go back to the original example script from our repo and copy paste the code snippet..

**Comment by lindnemi** [comment]
Did you solve your issue?

**Comment by CRHENS** [comment]
No, it didn't. I am unable to solve it. The only positive thing is: now I
am able to add force to all nodal dynamics (code attached), however unable
to force a single node.

Best
Chitta

**Comment by lindnemi** [comment]
Hey Chitta, it appears you just replied to the github e-mail. Unfortunately, the attached code didn't get forwarded to the issue. Could you post it here?

**Comment by CRHENS** [comment]
I am unable to solve it. The only positive thing is: now I am able to add
force to all nodal dynamics (code attached), however unable to force a
single node.

**Comment by lindnemi** [comment]
With "here" i meant the issue on github that sends you these notifications: https://github.com/PIK-ICoN/NetworkDynamics.jl/issues/74

**Comment by lindnemi** [comment]
Hello, unfortunately this issue went unnoticed for a while. Could you solve your problem?

One possible solution is to define two different vertices: `kuramoto_vertex` and `perturbed_kuramoto_vertex`. Then you will create a list of vertices like this:

```julia
vertex_list = Array{VertexFunction}[kuramoto_vertex for v in vertices(g)]
vertex_list[perturbation_index] = perturbed_kuramoto_vertex
```

You should also take a look at this example in the documentation: https://pik-icon.github.io/NetworkDynamics.jl/dev/heterogeneous_system/

**Comment by lindnemi** [comment]
I will close this issue now, i hope it helped. If you have further question don't hesitate to open a new issue.

**Comment by CRHENS** [comment]
Thanks for help :)  However, I fail to solve the problem.
It takes a huge time to understand the documentation. When I change a
little in the code, and it does not work. So  I keep it aside at this
moment.

Best
Chitta
