### ISSUE TITLE
Strange allocations in 1.6

### ISSUE THREAD

**Issue by lindnemi** [PIK-ICoN/NetworkDynamics.jl#81]
Measuring allocations of the main loops with `@allocated nd(dx, x, nothing, 0.)` returns `(1 allocation: 304 bytes)` on julia v1.6 and causes a test to fail:
- https://github.com/PIK-ICoN/NetworkDynamics.jl/blob/main/test/nd_ODE_Static_test.jl
- https://github.com/PIK-ICoN/NetworkDynamics.jl/runs/2673141705?check_suite_focus=true

On v1.5 everything works as expected (without allocations).

I tried `--track-allocations=user` and there are none. I tried `@allocated` on every line of nd_ODE_Static and there are none. I googled for related bug reports and found none.

**Comment by hexaeder** [comment]
This is a strange one. Maybe julia 1.6 handles function pointers in local scope a bit different? However I think this isn't a "real" problem. `@btime` with variable interpolatione (`$nd($dx, ..)`) shows no allocation. In #82 i've used two different strategies to fix this:
- explicit `const` where possible
- function barriers inside the `@testsets` (`const` is not possible in local scope)

at least locally this solves the problem for me. Still weird 🤷‍♂️
